### PR TITLE
Prepare for a release

### PR DESCRIPTION
**Pull request by madroach**
What needs to be done before release ?

- [ ] Do we feel confident about the api ?
  - [ ] Overwrite semantics of ``Map.put`` / ``Cursor.put`` ? #38
  - [ ] Keep using ``Not_found`` exception or switch to using options ?
- [ ] Is further testing necessary ?

### CODE REVIEW

**Comment by Drup** [comment]
This has been a while ... I think we should just release at this point, if only to gather feedback.

**Comment by madroach** [comment]
I agree completely. :-)

**Comment by madroach** [comment]
I prepared a [release](https://github.com/Drup/ocaml-lmdb/releases) and a [pull request](https://github.com/ocaml/opam-repository/pull/16223) for the opam-repository. OK to proceed and release?

**Comment by Drup** [comment]
:+1:

**Pull request merged**
