### PR TITLE
Add set_map_size API.

### PR DESCRIPTION
**Pull request by toots**

### CODE REVIEW

**Comment by Drup** [comment]
I was hoping the parameter to `Env.create` would be enough, given that calling it after open is potentially unsafe. 

This would really benefit from having a cleaner failure mode ...

**Comment by toots** [comment]
Well, at the very least that would allow to grow the db size on-the-fly..

**Comment by Drup** [comment]
Could we do something like counting the number of currently opened transaction and register a size change for when there are no more open transaction ?

Maybe I'm overthinking this.

**Comment by toots** [comment]
Personally, unless there is a compelling OCaml-specific reason, such as GC for instance like you do for Env initialization, I try to stick to the original C API as much as possible.

**Comment by Drup** [comment]
Wait, I'm already not doing that. :)

But fair enough, let's do it directly.

**Pull request merged**
